version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - "2333:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:latest
    ports:
      - "2334:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=figma_cache
      
  # 如果需要可视化管理工具
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "2335:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

volumes:
  redis_data:
  mongo_data: